### ISSUE TITLE
/param event commands not working

### ISSUE THREAD

**Issue by TheBearWannabe** [AscensionGameDev/Intersect-Engine#1057]
**Describe the bug**
When using the /param command within an event/common event, it's ignored and only the preceding command is displayed.

**Version Encountered**
0.7.0.126

**To Reproduce**

1. Open Intersect Editor. 
2. Under the top menu, navigate to Game Editors > Common Events
3. In the popup menu, create a new common event (RP Emote)
4. Double click on the newly created event, and double click within the commands box.
5. Under Dialogue, select "Add Chatbox Text"
6. In the settings, create the text as "\pn \param" (No quotes of course) and click OK.
7. Under "Commands" in the lower right hand corner of the event window, add /e to trigger the command in game.
8. Launch game, and use the command "/e is testing this command" in the chatbox
9. The command only displays the character name (\pn) 

**Expected behavior**
When using something like "\pn \param" it should append the message added by the player at the end. In this example, if the player entered "/e tests the issue" it would display in the chat as "(name) tests the issue"

**Screenshots**
![param0](https://user-images.githubusercontent.com/98631067/151646839-3b2a9bac-8f2e-40cf-a342-36bb9c493917.png)

**Logs**
No error logs

**Operating System:**
Windows 11

**Additional context**
When I moved to b7 this error seemed to have popped up, and it seems other people on the forums have experienced it as well. Not a major issue, but a tiny headache for sure. Thanks!

**Comment by Arufonsu** [comment]
This has already been fixed in the dev branch, will leave this issue up until the fix reaches the automated builds 👍🏽

**Comment by Arufonsu** [comment]
This is already been fixed in the dev branch, closing this issue since the fix will eventually reach the automated builds 👍🏽

**Comment by Arufonsu** [comment]
This is already fixed in the dev branch, closing this issue since the fix will eventually reach the automated builds 👍🏽

**Comment by TheBearWannabe** [comment]
@Arufonsu This issue still appears to be there as of prerelease 0.7.1.5 (4/18/22) any idea when it's being pushed? Thanks!
